events {
  worker_connections 1024;
}
http {
  server {
    listen 8080;
    server_name _;
    location / {
      proxy_pass https://tiktok.com;
      proxy_set_header Host www.google.com;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_ssl_server_name on;
    }
  }
}
